HFP-2992 Adjust to meet design created after pull request
h5p/h5p-editor-branching-scenario pull request #8
Opened 2021-01-22 22:29 UTC by otacke

- Add label translation strings for particular content types
- Add code to override label/description depending on content type

2021-01-25 10:03 UTC, simondate commented
Can you remove this please? https://github.com/otacke/h5p-branching-scenario/blob/HFP-2992-adjust-to-design/semantics.json#L228-L245

2021-01-25 10:16 UTC, simondate commented on src/scripts/components/EditorOverlay.js
> +  modifyrequiresFinishingField(library = {}) {
modify**R**equiresFinishingField

2021-01-25 10:43 UTC, simondate requested changes
Everything looks good.

2021-01-25 10:43 UTC, simondate commented on src/scripts/components/EditorOverlay.js
> +    this.modifyrequiresFinishingField(library);
modify**R**equiresFinishingField

2021-01-25 10:43 UTC, simondate commented on src/scripts/components/EditorOverlay.js
> +  modifyrequiresFinishingField(library = {}) {
modify**R**equiresFinishingField

2021-01-25 11:27 UTC, otacke commented on src/scripts/components/EditorOverlay.js
> +    this.modifyrequiresFinishingField(library);
Whoops. Well spotted!

2021-01-25 13:13 UTC, otacke commented
@simondate I have fixed the camelCase issue and removed the redundant settings field.

2021-01-26 09:08 UTC, simondate approved these changes

2021-01-26 09:08 UTC, simondate commented on language/en.json
> +      "requiresFinishingVideoDescription": "Urges viewers to complete the video before proceeding with the scenario"
Urges -> Forces

2021-01-26 09:08 UTC, simondate commented on language/en.json
> +      "requiresFinishingCoursePresentationDescription": "Urges viewers to navigate all the way to the last slide of the presentation in order to proceed. This setting will not work for active surface
Urges -> Forces

2021-01-26 16:15 UTC, merged